export const FETCH_DAILY_WEATHER_REQUEST = 'FETCH_DAILY_WEATHER_REQUEST';
export const FETCH_DAILY_WEATHER_SUCCESS = 'FETCH_DAILY_WEATHER_SUCCESS';
export const FETCH_DAILY_WEATHER_FAILURE = 'FETCH_DAILY_WEATHER_FAILURE';
