export const CITY_WEATHER_SEVEN_DAYS_REQUEST = 'FETCH_CITY_WEATHER_SEVEN_DAYS_REQUEST';
export const CITY_WEATHER_SEVEN_DAYS_SUCCESS = 'FETCH_CITY_WEATHER_SEVEN_DAYS_SUCCESS';
export const CITY_WEATHER_SEVEN_DAYS_FAILURE = 'FETCH_CITY_WEATHER_SEVEN_DAYS_FAILURE';
